name: build and deploy release
on:
  release:
    types: [published]
jobs:
  build:
    if: github.repository == 'QW-Group/mvdsv'
    uses: ./.github/workflows/_build.yml
    with:
      deploy_type: release
      release_version: ${{ github.ref_name }}
    secrets: inherit
